version: '3.9'

services:

  db:
    image: postgres:14.3-alpine3.15
    container_name: db
    ports:
      - "5431:5432"
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
      POSTGRES_DB: market_base
    volumes:
      - ./logs:/var/log

  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: dj_api_diplom:latest
    container_name: app
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
    command: >
      bash -c "python manage.py migrate && gunicorn -b 0.0.0.0:8000 dj_api_diplom.wsgi:application"